// export const manufacturers = [
//     { id: 1,name: "Acura"},
//     { id: 2, name: 'Alfa Romeo' },
//     { id: 3, name: 'Aston Martin' },
//     { id: 4, name: 'Audi' },
//     { id: 5, name: 'Bentley' },
//     { id: 6, name: 'BMW' },
//     { id: 7,name: "Buick"},
//     { id: 8, name: 'Cadillac' },
//     { id: 9, name: 'Chevrolet' },
//     { id: 10, name: 'Chrysler' },
//     { id: 11, name: 'Citroen' },
//     { id: 12, name: 'Dodge' },
//     { id: 13,name: "Ferrari"},
//     { id: 14, name: 'Fiat' },
//     { id: 15, name: 'Ford' },
//     { id: 16, name: 'GMC' },
//     { id: 17, name: 'Honda' },
//     { id: 18, name: 'Hyundai' },
//     { id: 19,name: "Jaguar"},
//     { id: 20, name: 'Jeep' },
//     { id: 21, name: 'Kia' },
//     { id: 22, name: 'Lamborghini' },
//     { id: 23, name: 'Land Rover' },
//     { id: 24, name: 'Lexus' },
//     { id: 25, name: 'Lincoln' },
//     { id: 26, name: 'Maserati' },
//     { id: 27,name: "Mazda"},
//     { id: 28, name: 'McLaren' },
//     { id: 29, name: 'Mercedes-Benz' },
//     { id: 30, name: 'MINI' },
//     { id: 31, name: 'Mitsubishi' },
//     { id: 32, name: 'Nissan' },
//     { id: 33,name: "Porsche"},
//     { id: 34, name: 'Ram' },
//     { id: 35, name: 'Rolls-Royce' },
//     { id: 36, name: 'Subaru' },
//     { id: 37, name: 'Tesla' },
//     { id: 38, name: 'Toyota' },
//     { id: 39,name: "Volkswagen"},
//     { id: 40, name: 'Volvo' },
//     { id: 41, name: 'Vinfast' },
// ];

export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
  "Vinfast",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];